### ISSUE TITLE
Some landcover files can not be found

### ISSUE THREAD

**Issue by Haves1001** [lambdajack/sequentially-generate-planet-mbtiles#3]
First of all, thank you for this awesome project, this was exactly what I was looking for the whole time!

When the shapes are being read to write the .mbtiles the following error occurs. Is this to be expected or did the file locations change?
```
Bounding box -85, -85, -84, 85
Reading .shp ocean
Reading .shp urban_areas
Reading .shp ice_shelf
Reading .shp glacier
Sorting loaded shapes
Reading .pbf /pbf/95.osm.pbf
Unable to open landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp or landcover/ne_10m_urban_areas/ne_10m_urban_areas.SHP.
Unable to open landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp or landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.SHP.
Unable to open landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp or landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.SHP.
```

**Comment by lambdajack** [comment]
Hi Haves1001 - thanks for checking this out - glad I could help!

That is currently expected behaviour. Tilemaker looks for the urban/glaciated/antarctic shape files in two places.

See just above where the relevant shape files are loaded in. 

```
Reading .shp urban_areas
Reading .shp ice_shelf
Reading .shp glacier
```

I may add the same files in both locations just to make the error go away, in the future, however that will not change the planet.mbtiles output.
