### ISSUE TITLE
Street names are cut off on higher zoom levels

### ISSUE THREAD

**Issue by Haves1001** [lambdajack/sequentially-generate-planet-mbtiles#5]
I was able to successfully build a planet.mbtiles on my machine. When rendering the tiles with tileserver-gl I can see that on higher zoom levels the tiles borders are cutting of the highway numbers. Or at least neigbhoring tiles are not matching the cut off.

Is this to be expected due slicing that is being done for compartmentalizing the mbtile generation?

<img width="726" alt="image" src="https://user-images.githubusercontent.com/5406293/163236039-60f9c057-22ee-4955-a10b-0ed2efd51b15.png">

**Comment by Haves1001** [comment]
On second thought I think this might actually be a problem with tileserver-gl when serving png's instead of vector files. 
I will do some research if this might have to do something with the tileserver-gl version that I'm using.

**Comment by lambdajack** [comment]
Thanks for letting me.

I have checked on a couple of mbtiles files which I have generated using the programme and cannot replicate your issue with labels being cut off. I suspect (as you have alluded to above) that it may be a tileserver-gl style issue.

Please see below some screenshots which I have gathered using tileserver-gl for serving and MapLibre (similar to MapBox) for rendering the vector tiles on the front end. Images show various levels of increasing zoom.

![ulm1-1](https://user-images.githubusercontent.com/69592559/163257268-ebb00cdf-dc4b-4648-8b18-adeafbca454b.png)
![ulm2-1](https://user-images.githubusercontent.com/69592559/163257356-43f206e0-9c7f-45a3-a7ec-538c3980004b.png)
![ulm3-1](https://user-images.githubusercontent.com/69592559/163257367-e08350a9-e111-4051-a571-5464587b4c71.png)
![ulm4-1](https://user-images.githubusercontent.com/69592559/163257427-e4493ed4-68fa-4fc3-854f-ce1a971db02e.png)
![ulm5-1](https://user-images.githubusercontent.com/69592559/163257444-39fd5f9e-b8d6-4521-bbc1-e99566d65b1c.png)

Are you able to paste here a copy of the style.json you are using? I can put this against my own tiles and see if that replicates the issue.

**Comment by lambdajack** [comment]
In reference to your point re the slicing causing the issue - I don't think this is the case since any duplicate roads or areas are overwritten (rather than written next to) the data already there (thus leaving only one copy).

The last image in the post above is taken directly at a split line which goes straight through the middle of jungingen.

Whilst it looks okay to me, I am not local to that area and cannot confirm that it looks totally accurate - if you are more knowledgeable of the area and are able to let me know if it looks okay or otherwise - I would very much appreciate your input! :D
