### ISSUE TITLE
Problem creating directories

### ISSUE THREAD

**Issue by etresoft** [lambdajack/sequentially-generate-planet-mbtiles#7]
Failed to run on the first try. This patch seemed to fix it.

[patch1.txt](https://github.com/lambdajack/sequentially-generate-planet-mbtiles/files/8526615/patch1.txt)

**Comment by lambdajack** [comment]
Hi @etresoft - thanks for submitting an issue.

Can you please provide specifically the error you got, os environment, version etc. I've just run it (up to the unzipping stage which you have suggested to patch) and it worked on these environments (stock Ubuntu and Fedora).

I've looked at your patch and wonder if that change is necessary because of a problem earlier in the programme? The file structure should be taken care of early on.

Are you using a custom dir in the config file? 

Apologies for the questions on a simple suggestion, but I would like to understand why that worked for you as much as possible - I'd like the programme to be as reliable as possible for other users and only have a limited number of test environments available to me here.

Also, feel free to submit a pull request with your suggested change - many thanks for taking a look at this.

**Comment by etresoft** [comment]
Long running, multi-stage tasks (i.e. anything involving OSM) are inherently fragile. The more robust each stage is, the better. In general, it is better to attempt an operation and then handle any potential failure. Any sequence of checking first and then attempting an operation is a race condition.

I have no idea why it failed initially. I'm not familiar with go and this project, so I did have a couple of initial failures simply from doing it wrong. I have been unable to find any documentation of how os.Mkdir behaves if a directory already exists. So this seemed like an easy solution.

I'm using default settings in the config file I guess. I have not made any changes to the default config file and it is virtually empty. Not sure if that is correct or not.

I'm not willing to do pull requests at this time. I'm dealing with a stalker situation and forgot that GitHub is trying to be a social media site. My previous purge of 59 repositories was insufficient. I shouldn't have even opened this issue. Please close it, and delete it, if possible. Thanks. Sorry for the trouble.

**Comment by lambdajack** [comment]
> Long running, multi-stage tasks (i.e. anything involving OSM) are inherently fragile. The more robust each stage is, the better. In general, it is better to attempt an operation and then handle any potential failure. Any sequence of checking first and then attempting an operation is a race condition.
> 
> I have no idea why it failed initially. I'm not familiar with go and this project, so I did have a couple of initial failures simply from doing it wrong. I have been unable to find any documentation of how os.Mkdir behaves if a directory already exists. So this seemed like an easy solution.
> 
> I'm using default settings in the config file I guess. I have not made any changes to the default config file and it is virtually empty. Not sure if that is correct or not.
> 
> I'm not willing to do pull requests at this time. I'm dealing with a stalker situation and forgot that GitHub is trying to be a social media site. My previous purge of 59 repositories was insufficient. I shouldn't have even opened this issue. Please close it, and delete it, if possible. Thanks. Sorry for the trouble.

............

Hi @etresoft I'm writing this comment before deleting in case Github emails you copies of comments etc.

Sorry to hear about that situation of yours. I will delete the issue.

You're always welcome here should you want to make a pr or open up an issue in the future.
